# fly.toml app configuration file generated for irrigation-be on 2025-06-28T16:00:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'irrigation-be'
primary_region = 'fra'

[env]
SPRING_PROFILES_ACTIVE = "prod"
SPRING_DATASOURCE_URL = "jdbc:postgresql://irrigation-db.internal:5432/postgres"
SPRING_DATASOURCE_USERNAME = "postgres"
SPRING_DATASOURCE_PASSWORD = "8vWAohIFgUYh2c9"
SPRING_JPA_HIBERNATE_DDL_AUTO = "update"

[build]
  dockerfile = "Dockerfile.fly"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
